import { Command } from 'commander';
import chalk from 'chalk';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { getRepoRoot } from '../core/git.js';
import { get } from '../core/config.js';

const PROVIDER_ENV_VARS: Record<string, string> = {
  anthropic: 'ANTHROPIC_API_KEY',
  openai: 'OPENAI_API_KEY',
  gemini: 'GEMINI_API_KEY',
  ollama: '', // no key needed
};

function buildWorkflowYaml(provider: string, failOn: string): string {
  const envKey = PROVIDER_ENV_VARS[provider] ?? 'GEMINI_API_KEY';
  const secretName = envKey; // same name by convention
  const isOllama = provider === 'ollama';

  const envBlock = isOllama
    ? ''
    : `
    env:
      ${envKey}: \${{ secrets.${secretName} }}`;

  return `# Auto-generated by git-ai ci
# Docs: https://github.com/Malikasadjaved/git-ai
name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write   # required for --gh-comment

jobs:
  review:
    name: git-ai review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history for branch diff

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install git-ai
        run: npm install -g @malikasadjaved/git-ai
${isOllama ? '' : `
      - name: Configure git-ai
        run: |
          git-ai setup --provider ${provider} --skip-hooks
`}
      - name: Run AI Code Review
        run: git-ai review --full --base \${{ github.base_ref }} --json --fail-on ${failOn} --gh-comment${envBlock}
`;
}

export const ciCommand = new Command('ci')
  .description('Generate a GitHub Actions workflow for automated AI code review')
  .option('--write', 'Write workflow to .github/workflows/git-ai-review.yml')
  .option(
    '--provider <provider>',
    'AI provider to use in CI (anthropic|openai|gemini|ollama)',
    'gemini',
  )
  .option(
    '--fail-on <severity>',
    'Severity level that causes CI to fail (critical|warning|suggestion)',
    'critical',
  )
  .action(runCI);

export async function runCI(opts: {
  write?: boolean;
  provider?: string;
  failOn?: string;
}) {
  const provider = opts.provider ?? get('provider') ?? 'gemini';
  const failOn = opts.failOn ?? 'critical';
  const yaml = buildWorkflowYaml(provider, failOn);
  const envKey = PROVIDER_ENV_VARS[provider];

  if (opts.write) {
    try {
      const root = await getRepoRoot();
      const workflowDir = join(root, '.github', 'workflows');
      const filePath = join(workflowDir, 'git-ai-review.yml');

      mkdirSync(workflowDir, { recursive: true });

      if (existsSync(filePath)) {
        console.log(chalk.yellow('  ⚠  .github/workflows/git-ai-review.yml already exists — overwriting.'));
      }

      writeFileSync(filePath, yaml, 'utf-8');
      console.log(chalk.green('\n  ✓ Workflow written to .github/workflows/git-ai-review.yml\n'));

      if (envKey) {
        console.log(chalk.bold('  Next step — add your API key as a GitHub Secret:'));
        console.log(chalk.cyan(`\n    gh secret set ${envKey} --body "your-api-key-here"\n`));
        console.log(chalk.dim('  Or go to: GitHub repo → Settings → Secrets → Actions → New secret'));
        console.log(chalk.dim(`  Secret name: ${envKey}\n`));
      }

      console.log(chalk.bold('  What happens on every PR:'));
      console.log(chalk.dim('  1. git-ai reviews the full branch diff'));
      console.log(chalk.dim('  2. Findings are posted as a PR comment'));
      if (failOn !== 'suggestion') {
        console.log(chalk.dim(`  3. CI fails (blocks merge) if any ${failOn.toUpperCase()} findings exist\n`));
      }
    } catch (error) {
      console.error(chalk.red(`\n  ✗ ${(error as Error).message}`));
      process.exit(1);
    }
  } else {
    // Print to stdout — user can redirect
    console.log(chalk.dim('\n  # Pipe to a file:  git-ai ci > .github/workflows/git-ai-review.yml'));
    console.log(chalk.dim('  # Or write directly: git-ai ci --write\n'));
    console.log(yaml);

    if (envKey) {
      console.log(chalk.bold('\n  After adding the file, set your secret:'));
      console.log(chalk.cyan(`  gh secret set ${envKey} --body "your-api-key-here"\n`));
    }
  }
}
